export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const LOGOUT = 'LOGOUT';
export const SESSION_VALIDATED = 'SESSION_VALIDATED';
export const SESSION_REFRESHED = 'SESSION_REFRESHED';
export const CONFIG_LOADED = 'CONFIG_LOADED';
