export const BUDGET_ADDED = 'BUDGET_ADDED';
export const BUDGET_DELETED = 'BUDGET_DELETED';
export const CURRENT_BUDGET_SELECTED = 'CURRENT_BUDGET_SELECTED';
export const BUDGETS_LOADED = 'BUDGETS_LOADED';
export const START_EDIT_BUDGET = 'START_EDIT_BUDGET';
export const CANCEL_EDIT_BUDGET = 'CANCEL_EDIT_BUDGET';
export const SAVE_BUDGET = 'SAVE_BUDGET';
